@startuml
autonumber

title "1. DC discovering"

box "Data Center (Location X)" #LightBlue
participant "Message\nBroker\nCoordinator" as mbc
end box

queue ESB as esb

==Subscribe==

mbc -> esb++: subscribe to DC liveness messages
activate mbc
esb -> mbc--: ack
deactivate mbc

==Liveness notification==
loop configured timeout
mbc -> esb++: RegionID
note over esb
fanout/broadcast exchange
end note
activate mbc
esb -> mbc--: ack
deactivate mbc
end


==Consume==
loop
esb -> mbc++: DC liveness message (RegionID)
activate esb
mbc -> mbc++--: register region with Idle
mbc -> esb--: ack
deactivate esb
end
@enduml